# Default values for <chart-name>.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: "933060838752.dkr.ecr.eu-central-1.amazonaws.com/ploybot_sabaa2"
  tag: "latest"
containerPort: 8443
#database:
#  host: "<your-database-host>"
resources:
  limits:
    cpu: "500m"
    memory: "1024Mi"
  requests:
    cpu: "500m"
    memory: "512Mi"
