apiVersion: v1
kind: Service
metadata:
  name: {{ include "yolo5.fullname" . }}-service
spec:
  selector:
    app: yolo5
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP